# Site settings
name: Autonomy and Verification Laboratory
email:
author: Autonomy and Verification Laboratory

keywords: autonomous systems, robotics, artificial intelligence, formal verification, sensor systems, programming
description: The Autonomy and Verification Laboratory at the University of Liverpool, UK

# Only use this if you are serving your site via Github Pages
github:
  url: "https://autonomy-and-verification-uol.github.io/"

header: yes
header_sm: images/ahston-small.png
header_med: images/ahston-med.png
header_large: images/ahston-large.png
header_xl: images/ahston-xl.png


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml

# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff


# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: LivUni_AVLab
twitter_card: true
twitter_image: images/ahston-small.png                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Usernames for things


researchgate_username: Michael-Fishers-Autonomy-and-Verification-Lab-Michael-Fisher
