# Site settings
name: Autonomy and Verification Laboratory
email:
author: Autonomy and Verification Laboratory

keywords: autonomous systems, robotics, artificial intelligence, formal verification, sensor systems, programming, formal modelling
description: The Autonomy and Verification Laboratory at the University of Liverpool, UK

# Only use this if you are serving your site via Github Pages
#github:

  #url:  http://localhost:4000
url: "https://autonomy-and-verification-uol.github.io"
images: "https://autonomy-and-verification-uol.github.io/images/"

header: no
header_sm: images/ashton-small.png
header_med: images/ashton-med.png
header_large: images/ashton-large.png
header_xl: images/ashton-xl-desat.png


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

collections:
  events:
    output: true
  projects:
    output: false
  projects-previous:
    output: false
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

address:
  - line: University of Liverpool Ashton Building Ashton Street Liverpool L69 3BX United Kingdom

#Google API key
google_api_key: AIzaSyB1miEwJXVP4HydUImEL5ONmzvCL37_dBU

#### SEO Stuff

# Twitter Cards
twitter_user: LivUni_AVLab
twitter_card: true
twitter_image: images/ashton-home.png                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Usernames for things


researchgate_username: Autonomy-and-Verification-Lab-Michael-Fisher
